services:
  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    depends_on:
      - user-db
    environment:
      - ENV=development
      - MONGO_URI=mongodb://user-db:27017/user
    networks:
      - service-network
  product-service:
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - "8001:3000"
    depends_on:
      - product-db
    environment:
      - ENV=development
      - MONGO_URI=mongodb://product-db:27017/product
    networks:
      - service-network
  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - "8002:3000"
    environment:
      - ENV=development
    networks:
      - service-network
  user-db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - service-network
  product-db:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - service-network

networks:
  service-network:
